version: '3.1'

services:
  api:
    image: nanoninja/php-fpm:8.1
    depends_on:
      - mysql
      - mailhog
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:8000" -t="/var/www/html/public"

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mydata:/var/lib/mysql

  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '1025:1025'
        - '8025:8025'

volumes:
  mydata:
    driver: local